<?php

/**
 * This is used to add override image to the top of the page. 
 */

/**
 * Implements hook_preprocess_html().
 */
function git_tag_version_preprocess_html(&$vars) {
  $version = "7.x-1.x";
  drupal_add_css(
    "body {
      background-image: url('http://dummyimage.com/300x200/000/fff.png&text=" . $version . "'), 
                        url('". path_to_theme() . "/images/pretties.png') !important; 
      background-position: center top; 
      background-repeat: no-repeat;
      background-color: #083228;}",

        
    array(
      'group' => CSS_THEME,
      'type' => 'inline',
      'weight' => '9999',
    )
  );
}
